// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

var MyLambdaFunction = require('./index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
{
  "session": {
    "new": false,
    "sessionId": "SessionId.6b3979a5-ee9b-4d0a-baaf-b6d821b0c14f",
    "application": {
      "applicationId": "amzn1.ask.skill.16f10d38-ecfd-4d4c-b02b-85eee009a9ae"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHNEX73JN5R22W6MD4INDDPUPE6VDWFC2SNKQC6GJNVKOYYITMRSICP4GX5CTPRNCPORQ7HGVR4NMAFFEF34VPG7NDMFKCHYATDHWGSN5YSQHDLZXPDFMMEEKSRDBYDMCJNRONWDG5NSYVVXAHPFBZTXUJG62N5CVBX3PZFRNJDIX6ME7BPJVX6JUAX4OCMYNKHTWXDEIFPKQDA"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.826ecbcd-a76b-465a-a66d-e11e5cc52283",
    "intent": {
      "name": "CoffeeIntent",
      "slots": {}
    },
    "locale": "en-US",
    "timestamp": "2017-11-02T15:39:19Z"
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.16f10d38-ecfd-4d4c-b02b-85eee009a9ae"
      },
      "user": {
        "userId": "amzn1.ask.account.AHNEX73JN5R22W6MD4INDDPUPE6VDWFC2SNKQC6GJNVKOYYITMRSICP4GX5CTPRNCPORQ7HGVR4NMAFFEF34VPG7NDMFKCHYATDHWGSN5YSQHDLZXPDFMMEEKSRDBYDMCJNRONWDG5NSYVVXAHPFBZTXUJG62N5CVBX3PZFRNJDIX6ME7BPJVX6JUAX4OCMYNKHTWXDEIFPKQDA"
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
  "version": "1.0"
};

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
